[package]
name = "oclp_nft"
version = "0.1.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override = true }
suins = { git = "https://github.com/MystenLabs/suins-contracts.git", subdir = "packages/suins", rev = "releases/mainnet/core/v3" }

[addresses]
oclp = "0x0"